name: 'Levivilet/Hello World'
description: 'This is a simple hello world action'
author: Le Vivilet
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  token:
    description: Token used to fetch the repository.
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
